version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/
    overwrite: yes
permission:
  - object: /
    pattern: *
    # owner: ec2-user
    # group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/applicationStop.sh
      timeout: 60
      runas: root
