server:
  port: 8080

spring:
  application:
    name: demo-api
  cache:
    ehcache:
      config: "classpath:ehcache.xml"

aws:
  alb:
    dns: "https://dev.ui.mingming.shop"

---
spring:
  profiles: dev

aws:
  alb:
    dns: "https://dev.ui.mingming.shop"

---
spring:
  profiles: stg

aws:
  alb:
    dns: "https://stg.ui.mingming.shop"

---
spring:
  profiles: prd

aws:
  alb:
    dns: "https://ui.mingming.shop"